dist: trusty
sudo: required
language: bash
before_install:
before_install:
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-02/run.sh | bash
  - sudo apt-get install software-properties-common
  - sudo apt-add-repository ppa:ansible/ansible -y
  - sudo apt-get -y update
  - sudo apt-get install ansible -y
  - sudo pip install ansible-lint
  - mkdir /tmp/dist && wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip -P /tmp/dist/
  - unzip /tmp/dist/terraform_0.11.7_linux_amd64.zip -d /tmp/dist
  - rm /tmp/dist/terraform_0.11.7_linux_amd64.zip
  - sudo mv /tmp/dist/terraform /usr/bin
  - chmod +x /usr/bin/terraform
#  - curl -OL https://github.com/wata727/tflint/releases/download/v0.5.4/tflint_linux_amd64.zip > /tmp/
  - wget https://github.com/wata727/tflint/releases/download/v0.5.4/tflint_linux_amd64.zip -P /tmp/
  - unzip /tmp/tflint_linux_amd64.zip -d /tmp
  - rm /tmp/tflint_linux_amd64.zip
  - sudo mv /tmp/tflint /usr/bin
  - chmod +x /usr/bin/tflint
  - touch ~/.ssh/appuser.pub && touch ~/.ssh/appuser
  - packer validate -var-file=packer/variables.json.example packer/app.json
  - packer validate -var-file=packer/variables.json.example packer/db.json
  - cd packer/ && packer validate immutable.json
  - packer validate -var-file=variables.json.example ubuntu16.json
  - cd ../terraform/prod/ && terraform init -backend=false && terraform validate -var-file=terraform.tfvars.example ./
  - tflint --var-file=terraform.tfvars.example
  - cd ../stage/ && terraform init -backend=false && terraform validate -var-file=terraform.tfvars.example ./ 
  - tflint --var-file=terraform.tfvars.example
  - cd ../.. && ansible-lint ansible/playbooks/*.yml
notifications:
  slack:
    secure: I0CvVXGk2hS+MefPnsJuj6G6bxJQyJw/UebdElz3O5iN9mogcgsUHpkxhjvZL6a8aGKhKTJkr+msIi3loVO02YGY8RSQ7iwdd6lyQZU3+N9kWs/CIZ+VaLKmvladWqbC858dRCKK+v+tdUkJdXxYo/8hRw7LP3ygDR/KpwQdVj+Q+2Vt8EA/f3Jp7kPy+BlCPcuLIr2uauA1urciMrlfHGuISttEYkLtTMRhZyI/VrqCXfVC6exoUq2pVdWwFn1kY7aLxbFlw2UdahzYmZICGXq/t/L3ZSPHgEIbZiYpk0kA58dTvVNTc8kpHjf3uXCdlut7W49a8LCHhVOuTCAzHM8B8LE9p6xj4uzPyahxQt9+tQlGmTnOiorTIpivxLf2fOHZarlzrHxm2kK7R4MOyWo5aZ2JgPEoWKSmzWLinlXyB0Ta9e1OqlExS0TcltdLk5lV+KwpREM9T6SjR4sIx28vs+ghSmHClQhUMz6/nDBBMccy+erlqSRdbSd7GbSpNOlmqt+yjboJK7bi52iES6eatMEYlBPO8LgJBfnXy1trNpADPZ0Kq393W0o81a3gACRVXulCE8FgA4EjHjdQ16ApQGKLkGFvVvA981RK36DtMQXeY0lxgCNrLbp45cpGHjLn+oGju+LAiY39dZ1FPM7jfJLE6EYhOVfYGYun3mk=
